version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: shift-scheduler-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shifts
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/shift-scheduler-frontend
    container_name: shift-scheduler-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: shift-scheduler-db
    environment:
      POSTGRES_DB: shifts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
